export enum AlertType {
  INSUFFICIENT_FUND = 'INSUFFICIENT_FUND',
  GAME_SERVER_ERROR = 'GAME_SERVER_ERROR',
  GENERAL_INFO_POPUP = 'GENERAL_INFO_POPUP',
  TOAST_ALERT = 'TOAST_ALERT',
}

export enum INSUFFICIENT_FUND_REASONS {
  SIGN_UP_GRPC_AUTH_IFE = 'SIGN_UP_GRPC_AUTH_IFE',
  JOIN_BACK_AFTER_STAND_UP_IFE = 'JOIN_BACK_AFTER_STAND_UP_IFE',
  LEAVE_TABLE_IFE = 'LEAVE_TABLE_IFE',
  HAS_RUMMY_WALLET_BALANCE_FALSE_AFTER_ROUND_FINISHED_IFE = 'HAS_RUMMY_WALLET_BALANCE_FALSE_AFTER_ROUND_FINISHED_IFE',
  CAN_PLAY_AGAIN_FALSE_AFTER_ROUND_FINISHED_IFE = 'CAN_PLAY_AGAIN_FALSE_AFTER_ROUND_FINISHED_IFE',
  BEFORE_TABLE_JOIN_IFE = 'BEFORE_TABLE_JOIN_IFE',
  GRPC_AUTH_INSUFFICIENT_FUND_ERROR = 'GRPC_AUTH_INSUFFICIENT_FUND_ERROR',
  CANCEL_BATTLE_INSUFFICIENT_FUND_ERROR = 'CANCEL_BATTLE_INSUFFICIENT_FUND_ERROR',
  DEBIT_ERROR_INSUFFICIENT_FUND_ERROR = 'DEBIT_ERROR_INSUFFICIENT_FUND_ERROR',
  FINISH_BATTLE_INSUFFICIENT_FUND_ERROR = 'FINISH_BATTLE_INSUFFICIENT_FUND_ERROR',
  PLAYMORE_INSUFFICIENT_FUND_ERROR = 'PLAYMORE_INSUFFICIENT_FUND_ERROR',
  COLLUSION_DETECTED_INSUFFICIENT_FUND_ERROR = 'COLLUSION_DETECTED_INSUFFICIENT_FUND_ERROR',
}

export enum GAME_SERVER_ERROR_REASONS {
  SIGN_UP_GRPC_AUTH_AUTHENTICATION_GSE = 'SIGN_UP_GRPC_AUTH_AUTHENTICATION_GSE',
  SIGN_UP_GRPC_AUTH_WALLET_GSE = 'SIGN_UP_GRPC_AUTH_WALLET_GSE',
  CANCEL_BATTLE_GSE = 'CANCEL_BATTLE_GSE',
  CREATE_BATTLE_GSE = 'CREATE_BATTLE_GSE',
  FINISH_BATTLE_GSE = 'FINISH_BATTLE_GSE',
  ADD_CASH_GET_USER_BALANCE_GSE = 'ADD_CASH_GET_USER_BALANCE_GSE',
  ADD_CASH_TO_USER_RUMMY_WALLET_GSE = 'ADD_CASH_TO_USER_RUMMY_WALLET_GSE',
  EXIT_SUMMARY_GET_RUMMY_WALLET_GSE = 'EXIT_SUMMARY_GET_RUMMY_WALLET_GSE',
  SIGN_UP_ON_DIFF_LOBBY_NOT_ALLOWED = 'SIGN_UP_ON_DIFF_LOBBY_NOT_ALLOWED',
}

export enum Color {
  RED = 'red',
  GREEN = 'green',
  BLUE = 'blue',
  YELLOW = 'yellow',
}

export enum ColorHexCode {
  RED = '#dc0907',
  GREEN = '#0da207',
  BLUE = '#0052cc',
  YELLOW = '#fe9510',
  WHITE = '#ffffff',
  BLACK = '#000000',
}

export enum ButtonAction {
  GOTOLOBBY = 'gotolobby',
  OKAY = 'okay_server',
}

export enum PopupType {
  TOP_TOAST_POPUP = 'topToastPopup',
  TOAST_POPUP = 'toastPopup',
  COMMON_POPUP = 'commonPopup',
}

export enum PopupPriority {
  HIGH = 'high',
  MEDIUM = 'medium',
  LOW = 'low',
}
