export const CONFIG = Object.freeze({
  WIN_RATIO_MIN: 0.8,
  WIN_RATIO_MAX: 1.2,
  REDIS_CLEAR_TIMEOUT: 5400,
  ROBOT_BID_TIMER: 2000,
  TUTORIAL_BID_TIMER: 6000,
  TURN_TIMER: 10000,
  GAME_STARTNEW: 6000,
  GAME_START: 15000,
  CREATE_BATTLE_TIME: 3000,
  TIPS_SHOW_TIME: 8,
  TIPS_REMOVE_TIME: 5000,
  TUTORIAL_TURN_TIMER: 10,
  WIN_TIMER: 2000,
  BID_TIMER: 10000,
  ROBOT_TIMER: 2,
  ROBOT_TURN_TIMER: 1000,
  FORCE_WIN_TURN: 2,
  LOCK_IN_PERIOD: 5,
  bonusCallsEnabled: true,
  bonusCalls: 8,
  bidLimitEnabled: false,
  bidLimit: 2,
  redistribution_global: false,
  redistribution_lobbies: [1],
  REDIS_DEFAULT_EXPIRY: 5400, // 1.5 hr
  LOBBY_EXPIRY: 86400, // one day
  COUNTRY: 'IN',
  IMWPM:
    "You don't have sufficient amount in your MPL wallet. Please add money and come back again. Thank you!",
  GSSP: 'Game score submission in progress..',
  GSDM: 'There was an error in debiting from your MPL wallet. Please try again later!',
  REBUY_POPUP_TEXT:
    '#20 Rs will be debited from Wallet.$ Are you sure you want to Rejoin?',
  REBUY_INVALID_POPUP: 'Table is not open, please join another table',
  MUTANT_APPTYPE: 'MUTANT',
  CGS_NAME: 'service-card-games',
});
